branch-defaults:
  default:
    environment: backendExpPgKnex1-env
  master:
    environment: backendExpPgKnex1-env
environment-defaults:
  backendExpPgKnex1-env:
    branch: master
    repository: backend-exp-pg-knex
global:
  application_name: backend-exp-pg-knex-1
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Node.js running on
    64bit Amazon Linux/4.3.0
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
